<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Jig.SharedKernel\Jig.SharedKernel.csproj" />
    <ProjectReference Include="..\Jig.Modules.Users.Contracts\Jig.Modules.Users.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FastEndpoints" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Jig.Modules.Users.Tests" />
  </ItemGroup>
</Project>
