#!/usr/bin/env bun
// Generates a typed TypeScript client from the API's own OpenAPI spec, so the wire contracts a
// caller depends on come from the source of truth and cannot silently drift (ADR-0006, and the
// promise Part 0 made). It boots the app, dumps the spec, and emits the client. Deterministic:
// CI reruns it and fails on any diff.

import { mkdir } from "node:fs/promises";
import { dirname } from "node:path";

const PORT = 5199;
const SPEC_URL = `http://localhost:${PORT}/swagger/v1/swagger.json`;
const SPEC_PATH = "tools/codegen/openapi.json";
const OUT_PATH = "clients/typescript/api.ts";

async function dumpSpec(): Promise<any> {
  const proc = Bun.spawn(
    ["dotnet", "run", "--project", "src/Jig.Host", "--no-launch-profile", "--configuration", "Release"],
    {
      env: { ...process.env, ASPNETCORE_URLS: `http://localhost:${PORT}`, ASPNETCORE_ENVIRONMENT: "Development" },
      stdout: "ignore",
      stderr: "ignore",
    },
  );
  try {
    for (let i = 0; i < 120; i++) {
      try {
        const res = await fetch(SPEC_URL);
        if (res.ok) return await res.json();
      } catch {
        // not up yet
      }
      await Bun.sleep(1000);
    }
    throw new Error("the app did not serve the OpenAPI spec in time");
  } finally {
    proc.kill();
    await proc.exited;
  }
}

const refName = (ref: string): string => ref.split("/").pop()!;

function tsType(schema: any): string {
  if (!schema) return "void";
  if (schema.$ref) return refName(schema.$ref);
  switch (schema.type) {
    case "string": return "string";
    case "integer":
    case "number": return "number";
    case "boolean": return "boolean";
    case "array": return `${tsType(schema.items)}[]`;
    case "object": return "Record<string, unknown>";
    default: return "unknown";
  }
}

function emitInterfaces(schemas: Record<string, any>): string {
  return Object.keys(schemas).sort().map((name) => {
    const s = schemas[name];
    const required: string[] = s.required ?? [];
    const props = Object.keys(s.properties ?? {}).map((p) => {
      const opt = required.includes(p) ? "" : "?";
      return `  ${p}${opt}: ${tsType(s.properties[p])};`;
    }).join("\n");
    return `export interface ${name} {\n${props}\n}`;
  }).join("\n\n");
}

const jsonSchemaOf = (node: any): any => node?.content?.["application/json"]?.schema;

function emitPaths(paths: Record<string, any>): string {
  const routes = Object.keys(paths).sort().map((route) => {
    const ops = paths[route];
    const methods = Object.keys(ops).sort().map((method) => {
      const op = ops[method];
      const pathParams = (op.parameters ?? []).filter((p: any) => p.in === "path");
      const params = pathParams.length
        ? `{ ${pathParams.map((p: any) => `${p.name}: ${tsType(p.schema)}`).join("; ")} }`
        : "Record<string, never>";
      const body = jsonSchemaOf(op.requestBody);
      const bodyType = body ? tsType(body) : "never";
      const ok = op.responses?.["200"] ?? op.responses?.["201"];
      const respType = ok ? tsType(jsonSchemaOf(ok)) : "void";
      return `    ${method}: { params: ${params}; body: ${bodyType}; response: ${respType} };`;
    }).join("\n");
    return `  "${route}": {\n${methods}\n  };`;
  }).join("\n");
  return `export interface paths {\n${routes}\n}`;
}

const spec = await dumpSpec();
delete spec.servers; // environment-specific; excluded so the committed spec is deterministic.

await mkdir(dirname(SPEC_PATH), { recursive: true });
await Bun.write(SPEC_PATH, JSON.stringify(spec, null, 2) + "\n");

const header = "// <auto-generated> Generated from the OpenAPI spec by tools/codegen/generate-client.ts. Do not edit.\n";
const out = [
  header,
  emitInterfaces(spec.components?.schemas ?? {}),
  "",
  emitPaths(spec.paths ?? {}),
  "",
].join("\n");

await mkdir(dirname(OUT_PATH), { recursive: true });
await Bun.write(OUT_PATH, out);

console.log(`Wrote ${SPEC_PATH} and ${OUT_PATH}`);
