// <auto-generated> Generated from the OpenAPI spec by tools/codegen/generate-client.ts. Do not edit.

export interface CreateUserRequest {
  name: string;
  email: string;
}

export interface DevTokenRequest {
  subject?: string;
  scopes?: string[];
}

export interface GetUserRequest {

}

export interface ProblemDetails {
  type?: string;
  title?: string;
  status?: number;
  instance?: string;
  traceId?: string;
  detail?: string;
  errors?: ProblemDetails_Error[];
}

export interface ProblemDetails_Error {
  name?: string;
  reason?: string;
  code?: string;
  severity?: string;
}

export interface UserNotificationsResponse {
  userName?: string;
  messages?: string[];
}

export interface UserResponse {
  id?: string;
  name?: string;
  email?: string;
}

export interface paths {
  "/dev/token": {
    post: { params: Record<string, never>; body: DevTokenRequest; response: void };
  };
  "/v1/me": {
    get: { params: Record<string, never>; body: never; response: UserResponse };
  };
  "/v1/users": {
    get: { params: Record<string, never>; body: never; response: UserResponse[] };
    post: { params: Record<string, never>; body: CreateUserRequest; response: UserResponse };
  };
  "/v1/users/{id}": {
    get: { params: { id: string }; body: never; response: UserResponse };
  };
  "/v1/users/{id}/notifications": {
    get: { params: { id: string }; body: never; response: UserNotificationsResponse };
  };
}
