<Project>
  <ItemGroup>
    <ProjectReference Include="$(MSBuildThisFileDirectory)..\tools\analyzers\Jig.Analyzers\Jig.Analyzers.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)..\tools\analyzers\Jig.Analyzers\ArchLayers.txt" />
  </ItemGroup>
</Project>
